# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config_path = "config/vagrant"
  config.vm.hostname = "elegin.dev"
  config.vm.network :private_network, ip: "192.168.42.42"
  config.vm.synced_folder "./elegin.dev", "/var/www/elegin.dev", id: "web-root",
      owner: "vagrant",
      group: "www-data",
      mount_options: ["dmode=775,fmode=664"]

  config.vm.provider "virtualbox" do |v|
    v.memory = 16384 #4096
    v.cpus = 4 #2
  end



  config.ssh.forward_agent = true


  config.vm.provision :shell, path: "#{config_path}/build_dependency_setup.sh"
  config.vm.provision :shell, path: "#{config_path}/postgresql_setup.sh"
  config.vm.provision :shell, path: "#{config_path}/apache2_setup.sh"
  config.vm.provision :shell, path: "#{config_path}/php7_setup.sh"
  config.vm.provision :shell, path: "#{config_path}/composer_setup.sh"






  # PostgreSQL Server port
  config.vm.network "forwarded_port", host: 15432, guest: 5432



end
